### ISSUE TITLE
clusters.js error

### ISSUE THREAD

**Issue by nichoice** [edf-hpc/slurm-web#199]
slurm version: 17.11.12
slurm-web version 2.2.3
I am deploying slurm-web in the container. But the page is blank.
`Uncaught TypeError: $.ajax(...).success is not a function
    at retrieveClusterInformations (clusters.js:45)
    at async.min.js:1
    at async.min.js:1
    at Array.forEach (<anonymous>)
    at _each (async.min.js:1)
    at async.each (async.min.js:1)
    at _asyncMap (async.min.js:1)
    at Object.map (async.min.js:1)
    at Object.init (clusters.js:117)
    at index.js:143
jquery.min.js:4 GET http://192.168.1.62:8081/slurm-restapi/cluster 500 (Internal Server Error)`

apache2  error.log:
`Traceback (most recent call last):
  File "slurmrestapi.py", line 41, in <module>
    from auth import (User, authentication_verify,
  File "/usr/share/slurm-web/restapi/auth.py", line 153, in <module>
    abort.mapping.update({403: CORSForbidden})
AttributeError: 'function' object has no attribute 'mapping'`

what should I do

**Comment by nichoice** [comment]
- [ ]
