### ISSUE TITLE
Make use of cache mechanism optional

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#73]
In v2, a cache mechanism has been added. Its use is mandatory, in the current state of affairs. The goal is to make it optional, so that one can deploy without installing Redis and so on.

**Comment by rezib** [comment]
In restapi.conf, I have:

```
[config]
cache = disable

#[cache]
# address for Redis server (default to host=localhost, port=6379)
#redis_host = localhost
#redis_port = 6379
# TTL for jobs (default to 10 seconds)
#jobs_expiration = 10
# TTL for other informations (default to 86400 seconds = 24 hours)
#global_expiration = 86400
```

But I get this error in the logs:

```
[error] Error while retrieving parameter, section not found, check restapi.conf : No section: 'cache'
```

The cache section should not be required in config file as soon as cache is disabled.

**Comment by rezib** [comment]
Then still with:

```
# Set to 'enable' to activate cache.
cache = disable
```

(and `[cache]` section uncommented)

I have this error in the logs:

```
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121] mod_wsgi (pid=42585): Target WSGI script '/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi' cannot be loaded as Python module.
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121] mod_wsgi (pid=42585): Exception occurred processing WSGI script '/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi'.
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121] Traceback (most recent call last):
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121]   File "/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi", line 4, in <module>
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121]     from slurmrestapi import app as application
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121]   File "/usr/share/slurm-web/restapi/slurmrestapi.py", line 41, in <module>
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121]     from cache import cache
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121]   File "/usr/share/slurm-web/restapi/cache.py", line 74, in <module>
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121]     r = redis.Redis(redis_host, redis_port)
[Wed Feb 03 16:49:39 2016] [error] [client 10.116.139.121] NameError: name 'redis_host' is not defined
```

Looks like it tries to use redis even when cache is disabled...

**Comment by rezib** [comment]
Since I'm not able to disable the cache, I set:

```
[config]
cache = disable

[cache]
# address for Redis server (default to host=localhost, port=6379)
redis_host = localhost
redis_port = 6379
# TTL for jobs (default to 10 seconds)
#jobs_expiration = 10
# TTL for other informations (default to 86400 seconds = 24 hours)
#global_expiration = 86400
```

Then I get in logs:

```
[Wed Feb 03 17:03:30 2016] [error] Error while retrieving jobs_expiration parameter, not found, check restapi.conf : No option 'jobs_expiration' in section: 'cache'
[Wed Feb 03 17:03:30 2016] [error] Error while retrieving global_expiration parameter, not found, check restapi.conf : No option 'global_expiration' in section: 'cache'
```

and:

```
[Wed Feb 03 17:03:40 2016] [error] ERROR:slurmrestapi:Exception on /jobs [POST]
[Wed Feb 03 17:03:40 2016] [error] Traceback (most recent call last):
[Wed Feb 03 17:03:40 2016] [error]   File "/usr/lib/python2.6/dist-packages/flask/app.py", line 861, in wsgi_app
[Wed Feb 03 17:03:40 2016] [error]     rv = self.dispatch_request()
[Wed Feb 03 17:03:40 2016] [error]   File "/usr/lib/python2.6/dist-packages/flask/app.py", line 696, in dispatch_request
[Wed Feb 03 17:03:40 2016] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Feb 03 17:03:40 2016] [error]   File "/usr/share/slurm-web/restapi/cors.py", line 53, in wrapped_function
[Wed Feb 03 17:03:40 2016] [error]     resp = make_response(f(*args, **kwargs))
[Wed Feb 03 17:03:40 2016] [error]   File "/usr/share/slurm-web/restapi/auth.py", line 223, in inner
[Wed Feb 03 17:03:40 2016] [error]     resp = f(*args, **kwargs)
[Wed Feb 03 17:03:40 2016] [error]   File "/usr/share/slurm-web/restapi/cache.py", line 103, in inner
[Wed Feb 03 17:03:40 2016] [error]     expiration = jobs_expiration
[Wed Feb 03 17:03:40 2016] [error] NameError: global name 'jobs_expiration' is not defined
```

What do you mean by "_default_" in the comments of the config file if those parameters *must* be set in config file? :) Those values must be *real* default, it means they don't have to be set explicitely in config file.

**Comment by Lorel** [comment]
should be definitely fixed

**Comment by rezib** [comment]
Works for me with last commit.
