### ISSUE TITLE
Better handling of failed connection to redis

### ISSUE THREAD

**Issue by rezib** [edf-hpc/slurm-web#97]
Currently, when case is enable and redis server is not available, the backend fails with the following stacktrace:

```
[Mon Feb 08 14:30:46 2016] [error] Traceback (most recent call last):
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/python2.6/dist-packages/flask/app.py", line 861, in wsgi_app
[Mon Feb 08 14:30:46 2016] [error]     rv = self.dispatch_request()
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/python2.6/dist-packages/flask/app.py", line 696, in dispatch_request
[Mon Feb 08 14:30:46 2016] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/share/slurm-web/restapi/cors.py", line 53, in wrapped_function
[Mon Feb 08 14:30:46 2016] [error]     resp = make_response(f(*args, **kwargs))
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/share/slurm-web/restapi/auth.py", line 224, in inner
[Mon Feb 08 14:30:46 2016] [error]     resp = f(*args, **kwargs)
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/share/slurm-web/restapi/cache.py", line 85, in inner
[Mon Feb 08 14:30:46 2016] [error]     if r.exists(cache_key):
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/pymodules/python2.6/redis/client.py", line 529, in exists
[Mon Feb 08 14:30:46 2016] [error]     return self.execute_command('EXISTS', name)
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/pymodules/python2.6/redis/client.py", line 330, in execute_command
[Mon Feb 08 14:30:46 2016] [error]     **options
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/pymodules/python2.6/redis/client.py", line 315, in _execute_command
[Mon Feb 08 14:30:46 2016] [error]     self.connection.send(command, self)
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/pymodules/python2.6/redis/client.py", line 82, in send
[Mon Feb 08 14:30:46 2016] [error]     self.connect(redis_instance)
[Mon Feb 08 14:30:46 2016] [error]   File "/usr/lib/pymodules/python2.6/redis/client.py", line 62, in connect
[Mon Feb 08 14:30:46 2016] [error]     raise ConnectionError(error_message)
[Mon Feb 08 14:30:46 2016] [error] ConnectionError: Error 111 connecting localhost:6379. Connection refused.
```

The backend API should fallback to cache disable setting and warn with clear message in the logs.

**Comment by rezib** [comment]
Fixed with 715013a.
